apiVersion: v1
kind: Service

metadata:
  name: flight-price-service

spec:
  selector:
    app: flight-price-api

  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001

  type: NodePort